#!/bin/bash

show_help()
{
	echo "Usage: $(basename $0) [options] <image>

Options:
    -o: Use original image (not daily) and don't dist-upgrade"
}

usage()
{
	show_help
	exit 1
}

OPTIONS=

while getopts "?od" o; do
    case "$o" in
        \?)
            show_help
            exit 0
            ;;
        o)
            OPTIONS="$OPTIONS -r ubuntu -u"
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))


if [ $# -ne 1 ]; then
	usage
fi

RELEASE=$1

uvt-latest -n tester -d $OPTIONS $RELEASE
