#!/bin/bash

set -eu

show_help()
{
	echo "Usage: $(basename $0) [options] <image>

Options:
	-n <name>: Specify the name of the VM to create (default same as image name)
    -r <remote>: Specify which remote to use (default ubuntu-daily)
    -u: Don't dist-upgrade
    -d: Add debug symbol repositories
    -s: Sync image first"
}

usage()
{
	show_help
	exit 1
}

CONTAINER_NAME=
REMOTE=daily
DIST_UPGRADE=1
DEBUG_SYMBOLS=0
SYNC=0

while getopts "?n:r:uds" o; do
    case "$o" in
        \?)
            show_help
            exit 0
            ;;
        n)
            CONTAINER_NAME=$OPTARG
            ;;
        r)
            REMOTE=$OPTARG
            ;;
        u)
            DIST_UPGRADE=0
            ;;
        d)
            DEBUG_SYMBOLS=1
            ;;
        s)
            SYNC=1
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ $# -ne 1 ]; then
	usage
fi

IMAGE=$1
if [ -z "$CONTAINER_NAME" ]; then
    CONTAINER_NAME=$IMAGE
fi

REMOTE_ARG=label=$REMOTE
if [ ! "$REMOTE" == "daily" ]; then
    REMOTE_ARG=
fi

if [ $SYNC -eq 1 ]; then
    source_arg="--source http://cloud-images.ubuntu.com/daily"
    if [ ! "$REMOTE" == "daily" ]; then
        source_arg=
    fi

    echo "Syncing $IMAGE $REMOTE"
    uvt-simplestreams-libvirt sync $source_arg arch=amd64 release=$IMAGE
fi

echo "Deleting old $CONTAINER_NAME"
uvt-kvm destroy $CONTAINER_NAME || true
echo "uvt-kvm create $CONTAINER_NAME arch=amd64 $REMOTE_ARG release=$IMAGE --password ubuntu"
uvt-kvm create $CONTAINER_NAME arch=amd64 $REMOTE_ARG release=$IMAGE --password ubuntu
uvt-kvm wait $CONTAINER_NAME
if [ $DEBUG_SYMBOLS -eq 1 ]; then
    release=$(uvt-kvm ssh $CONTAINER_NAME -- lsb_release -cs)
    version=$(uvt-kvm ssh $CONTAINER_NAME -- lsb_release -rs)
    echo "deb http://ddebs.ubuntu.com $release main restricted universe multiverse
    deb http://ddebs.ubuntu.com $release-updates main restricted universe multiverse
    deb http://ddebs.ubuntu.com $release-proposed main restricted universe multiverse" | \
    uvt-kvm ssh $CONTAINER_NAME -- sudo tee -a /etc/apt/sources.list.d/ddebs.list

    # if (( $(echo "$version >= 18.04" |bc -l) )); then
    #     uvt-kvm ssh $CONTAINER_NAME -- sudo apt install -y ubuntu-dbgsym-keyring
    # else
        uvt-kvm ssh $CONTAINER_NAME -- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622
    # fi
fi
echo "apt update"
uvt-kvm ssh $CONTAINER_NAME -- sudo apt update
if [ $DIST_UPGRADE -eq 1 ]; then
    echo "apt dist-upgrade -y"
    uvt-kvm ssh $CONTAINER_NAME -- sudo apt dist-upgrade -y
fi
uvt-kvm ssh $CONTAINER_NAME -- sudo apt autoremove -y
uvt-kvm ssh $CONTAINER_NAME
